site_name: Documentação Flutter Clean Architecture

theme:
  name: material

nav:
  - Início: index.md
  - Injeção/Inversão de dependências: dependency_injection.md
  - Roteamento com Flutter: roteamento.md

