site_name: Documentação

theme:
  name: material

nav:
  - Início: index.md

  - Core - Injeção/Inversão de dependências: dependency_injection.md
  - Core - Roteamento nomeado: roteamento.md
  - Config - Tradução/Internacionalização: localization.md
  - Config - Temas: themes.md

